### ISSUE TITLE
Extra Parenthesis in expressions

### ISSUE THREAD

**Issue by aoeu256** [berkerpeksag/astor#14]
In[15]: astor.to_source(ast.parse('1+2'))
Out[15]: '(1 + 2)'

**Comment by pmaupin** [comment]
@aoeu256 

Please close if the results are acceptable.

Thanks,
Pat

**Comment by leonardt** [comment]
I think the correct way to solve this issue is to implement precedence and associativity in the code generator using the proper rules for Python's syntax.

The `ctree` package does this for emitting c-code. Files of interest:
* Precedence/Associativity encoding: https://github.com/ucb-sejits/ctree/blob/master/ctree/precedence.py
* Computing whether parentheses are required when code generating a node: https://github.com/ucb-sejits/ctree/blob/master/ctree/c/codegen.py#L20-L37

**Comment by pmaupin** [comment]
Is there something wrong with the way the pretty printer does it now?

**Comment by leonardt** [comment]
@pmaupin Nope, just commenting w.r.t.
>>> The current codegen module doesn't know anything about precedence, and
AFAIK generates correct, compilable code that round-trips into the same
AST. You could give it some knowledge of precedence, but just remember
that a little knowledge is a dangerous thing :-)

I agree with you, just thought I'd provide a working example of how to extend the codegen to do it correctly.

**Comment by pmaupin** [comment]
But that comment was about a suggestion to do this in an (imo) half-assed fashion.

Later, I eventually bit the bullet and did it in what IMO was a correct fashion.  So if we need a separate example of how to do it correctly, I need to understand what about the current implementation isn't actually correct.

Thanks,
Pat

**Comment by leonardt** [comment]
I see, I was going off the context of purely this thread so I wasn't aware of that work. I would suggest tabling this discussion until it becomes an actual issue (i.e. a bug is found in your implementation). I was just walking through issues open w.r.t. the 0.6 release as I'd like to make the release happen (I am working on some projects that depend on this release)

**Comment by pmaupin** [comment]
Unfortunately, the original submitter never responded to "Please close if the results are acceptable." so the issue's still just hanging out there.  My fix will be two years old in a month, with no complaints since then, so it might be best to close it so it doesn't attract further well-meaning attention based on out-of-date results.  I'll leave that decision up to @berkerpeksag

**Comment by berkerpeksag** [comment]
Yeah, let's close this issue :)
