### ISSUE TITLE
Remove Python 2.6 and 3.2 support.

### ISSUE THREAD

**Issue by berkerpeksag** [berkerpeksag/astor#39]

**Comment by pmaupin** [comment]
I'm completely with you on 3.2.

2.6 is extremely widely used in production, e.g. at my workplace.  Personally, I am testing against 2.6, 2.7, 3.3, 3.4, and 3.5.

I have no real heartburn about removing automated tests for 2.6, but I would like to verify it runs before doing a real release.

**Comment by ztane** [comment]
2.6 and 3.2 pretty much go hand in hand, the operating systems stuck with 2.6 would have 3.2 as the Python 3.

**Comment by pmaupin** [comment]
Au contraire!  Most operating systems stuck on 2.6 don't have 3.anything.

**Comment by ztane** [comment]
Ah indeed, but there are equally systems stuck with 3.2, namely older Debian stable. 3.1 and 3.0 are not even theoretically usable.

**Comment by pmaupin** [comment]
Right.  What I am discussing is an older OS, used in production, with older apps, used in production.  I submit that I have personal knowledge that 2.6 is still in this state in several organizations.  I don't personally know of any apps used in production using 3.2 in this state, and I suspect there really aren't that many, because of all the 2-to-3 migration issue.  People who stuck with old OSes likely stuck with old Python.

We are talking about the intersection of production apps that require astor (which is itself quite young), and that will benefit from the new release of astor, with systems that are stuck on 2.6 or 3.2.

I think the 2.6 is tiny yet extant, and the second case is non-existent, so I propose that this issue be modified to only drop 3.2.  If you have reasons to keep 3.2, then we should close the issue as premature and keep supporting both.

**Comment by berkerpeksag** [comment]
Fair enough :) Also, we are still supporting 2.6 in Hy(and astor is the power of the "hy --spy" command), so we can't just drop 2.6 support. Thanks for the responses!
